ALTER TABLE `fx_db`.`information_listdata` 
CHANGE COLUMN `field_1` `field_1` TEXT(4000) NULL DEFAULT NULL COMMENT '字段1' ,
CHANGE COLUMN `field_2` `field_2` TEXT(4000) NULL DEFAULT NULL COMMENT '字段2' ,
CHANGE COLUMN `field_3` `field_3` TEXT(4000) NULL DEFAULT NULL COMMENT '字段3' ,
CHANGE COLUMN `field_4` `field_4` TEXT(4000) NULL DEFAULT NULL COMMENT '字段4' ,
CHANGE COLUMN `field_5` `field_5` TEXT(4000) NULL DEFAULT NULL COMMENT '字段5' ,
CHANGE COLUMN `field_6` `field_6` TEXT(4000) NULL DEFAULT NULL COMMENT '字段6' ,
CHANGE COLUMN `field_7` `field_7` TEXT(4000) NULL DEFAULT NULL COMMENT '字段7' ,
CHANGE COLUMN `field_8` `field_8` TEXT(4000) NULL DEFAULT NULL COMMENT '字段8' ,
CHANGE COLUMN `field_9` `field_9` TEXT(4000) NULL DEFAULT NULL COMMENT '字段9' ,
CHANGE COLUMN `field_10` `field_10` TEXT(4000) NULL DEFAULT NULL COMMENT '字段10' ;
