/*评测报告新增题*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1251,'0',NULL,'项目评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1252,'1251',NULL,'模式评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1253,'1252',NULL,'项目定位',NULL,8,2,NULL,'e',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1254,'1252',NULL,'业务实质',NULL,8,2,NULL,'e',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1255,'1252',NULL,'可行性',NULL,2,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1256,'1251',NULL,'创新性评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1257,'1251',NULL,'市场地位领先性评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1258,'1251',NULL,'机会评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1259,'1258',NULL,'是否有机会',NULL,2,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1260,'1251',NULL,'产品服务评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1261,'1260',NULL,'产品服务用户体验',NULL,8,2,NULL,'e',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1262,'1260',NULL,'存在的主要问题是',NULL,8,2,NULL,'e',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1263,'1251',NULL,'收入模式评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1264,'1251',NULL,'销售方式评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1265,'1251',NULL,'技术领先性评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1266,'1263',NULL,'——',NULL,17,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1267,'1264',NULL,'——',NULL,17,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1381,'0',NULL,'团队评测 ',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1382,'1381',NULL,'团队核心能力评测 ',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1383,'1381',NULL,'CEO评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1384,'1383',NULL,'缺点',NULL,8,2,NULL,'e',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1385,'1381',NULL,'团队综合评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1386,'1381',NULL,'核心团队能力满足度评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1451,'0',NULL,'运营评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1453,'1451',NULL,'增资评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1454,'1451',NULL,'运营策略评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1455,'1451',NULL,'关键运营数据评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1456,'1451',NULL,'通过运营数据的重要发现（剔除非主营业务）',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1457,'1451',NULL,'通过运营数据判断该项目的投资阶段',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1458,'1451',NULL,'客户及收入评测（剔除非主营业务）',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1459,'1451',NULL,'成本及投入效率评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1460,'1451',NULL,'获客成本',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1461,'1458',NULL,'客户及收入评测（剔除非主营业务）',NULL,NULL,3,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1462,'1459',NULL,'成本及投入效率评测',NULL,NULL,3,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1561,'0',NULL,'竞争评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1562,'1561',NULL,'竞争格局评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1563,'1561',NULL,'竞争优势评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1564,'1561',NULL,'竞争壁垒评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1565,'1561',NULL,'竞争威胁评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1566,'1565',NULL,'主要竞争威胁来自',NULL,3,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1567,'1565',NULL,'差异化策略',NULL,18,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1568,'1565',NULL,'胜算度',NULL,18,2,'题号:1548;字段:field_1,field_2;','e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1951,'0',NULL,'融资评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1952,'1979',NULL,'融资假设的关键运营数据指标达成可行性',NULL,8,2,NULL,'e',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1953,'1982',NULL,'融资障碍度',NULL,8,2,NULL,'e',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1971,'0',NULL,'退出评测',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1972,'1975',NULL,'——',NULL,2,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1973,'1976',NULL,'——',NULL,2,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1974,'1977',NULL,'——',NULL,2,2,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1975,'1971',NULL,'法务方面是否存在上市硬伤',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1976,'1971',NULL,'财务方面是否存在上市硬伤',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1977,'1971',NULL,'上市是否存在政策限制',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1978,'1951',NULL,'本轮融资可以满足公司经营的时长',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1979,'1951',NULL,'融资假设的关键运营数据指标达成可行性',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1980,'1951',NULL,'融资估值合理性',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1981,'1951',NULL,'到隔一轮的融资估值及时间表',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1982,'1951',NULL,'融资障碍度',NULL,NULL,1,NULL,'e',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);





/*决策报告新增题*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3001,'0',NULL,'投资方案',3001.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3002,'3001',NULL,'投决会结果',3002.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3004,'3002',NULL,'投资金额',3004.000,19,2,'万元','p',0,NULL,NULL,NULL,NULL,NULL,0,'2','9,4',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3005,'3002',NULL,'增资及购买股权具体安排',3005.000,8,2,NULL,'p',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3006,'3002',NULL,'对赌或承诺条件',3006.000,8,2,NULL,'p',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3007,'3002',NULL,'董事会安排',3007.000,8,2,NULL,'p',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3008,'3001',NULL,'估值安排',3011.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3009,'3008',NULL,'投前估值',3012.000,19,2,'万元','p',0,NULL,NULL,NULL,NULL,NULL,0,'2','9,4',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3010,'3008',NULL,'股权占比',3013.000,19,2,'%','p',0,NULL,NULL,NULL,NULL,NULL,0,'3','3,2',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3011,'3008',NULL,'加速服务费占比',3014.000,19,2,'%','p',0,NULL,NULL,NULL,NULL,NULL,0,'3','3,2',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3012,'3008',NULL,'项目估值',3015.000,19,2,'万元','p',0,NULL,NULL,NULL,NULL,NULL,0,'2','9,4',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3013,'3001',NULL,'交割前事项',3021.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3015,'3001',NULL,'交割后事项',3031.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3017,'3001',NULL,'已有投资人投资条款的优化',3041.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3018,'3017',NULL,'已有投资人投资条款的优化',3042.000,8,2,NULL,'p',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3019,'3001',NULL,'星河投资方主体',3051.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3020,'3019',NULL,'星河投资方主体',3052.000,8,2,NULL,'p',0,'请填写',NULL,NULL,NULL,NULL,0,'1','50',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3021,'3001',NULL,'分期注资计划',3061.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3022,'3021',NULL,'分期注资计划',3062.000,10,2,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3023,'3001',NULL,'是否需要加急签约并付款',3071.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3024,'3023',NULL,'是否需要加急签约并付款',3072.000,5,2,NULL,'p',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3025,'0',NULL,'其他事宜',3081.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3026,'3025',NULL,'其他事宜',3082.000,NULL,1,NULL,'p',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (3027,'3026',NULL,'需要补充的事项',3083.000,8,2,NULL,'p',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000',NULL);



/*尽调报告新增题*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1813,'1812','NO8_1_11','企业法人信息',813.000,NULL,3,NULL,'d',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1814,'1813','NO8_1_11_1','公司名称',814.000,1,2,NULL,'d',0,'请输入公司名称',NULL,NULL,NULL,NULL,0,'1','50');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1815,'1813','NO8_1_11_2','法人',815.000,1,2,NULL,'d',0,'请输入法人名称',NULL,NULL,NULL,NULL,0,'1','30');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1816,'1813','NO8_1_11_3','成立时间',816.000,1,2,NULL,'d',0,NULL,NULL,NULL,NULL,NULL,0,'5',NULL);


UPDATE `fx_db`.`information_title` SET `placeholder`='请填写' WHERE `id`='1253';
UPDATE `fx_db`.`information_title` SET `placeholder`='请填写' WHERE `id`='1254';
UPDATE `fx_db`.`information_title` SET `placeholder`='请填写' WHERE `id`='1261';
UPDATE `fx_db`.`information_title` SET `placeholder`='请填写' WHERE `id`='1262';

