/*投资方案*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1266,'1202',NULL,'是否经历了转向',205.500,2,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1267,'1218',NULL,'产品服务用户体验',226.500,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');

/*团队*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1387,'1363',NULL,'达成该项目需要的核心能力不足部分的完善是否如期完成',272.100,2,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1388,'1363',NULL,'团队的执行力与创业当初比较是更优还是略逊',272.200,2,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1389,'1363',NULL,'项目转向后需要的核心能力有何变化？转向项目',272.300,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1390,'1363',NULL,'团队的创业文化是否形成',272.400,2,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);

/*运营*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1465,'1401',NULL,'运营数据对核心团队的验证',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (1463,'1402',NULL,'关键运营数据曲线变化（细分项目、拆分到年度、月度、周、日）',NULL,7,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`,`val_rule_formula`) VALUES (1464,'1402',NULL,'通过主营业务运营数据的重要发现',NULL,8,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,'1','2000',NULL);

INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1466,'1465',NULL,'运营数据好于判断的团队能力，原因是',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1467,'1465',NULL,'运营数据差于判断的团队能力，原因是',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1468,'1401',NULL,'运营数据对模式的验证',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1469,'1468',NULL,'运营数据验证模式的可行性',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1470,'1468',NULL,'运营数据验证模式存在的问题',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1471,'1401',NULL,'运营数据对核心技术的验证',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1472,'1471',NULL,'技术可行性验证方法',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1473,'1401',NULL,'运营数据对竞争格局判断的验证',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1474,'1473',NULL,'竞争是否导致运营数据增长趋缓或降低',NULL,2,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);


/*竞争*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1569,'1552',NULL,'核心竞争力构建进程',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1570,'1501',NULL,'主要竞争对手的变化',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1571,'1570',NULL,'主要竞争对手的变化',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1572,'1501',NULL,'潜在竞争威胁变化',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1573,'1572',NULL,'潜在竞争威胁变化',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1574,'1505',NULL,'护城河支点的构建进度',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1575,'1505',NULL,'增加竞争力的最有效措施',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1576,'1505',NULL,'对主要竞争威胁的对策是否验证',NULL,2,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1577,'1501',NULL,'竞争格局引发的要求',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1578,'1577',NULL,'需要增加的团队核心能力',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1579,'1577',NULL,'需要团队的学习能力',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1580,'1577',NULL,'需要的核心资源',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1581,'1577',NULL,'需要的资金投入',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');

/*市场与开发*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (3031,'0',NULL,'市场与开发',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (3032,'3031',NULL,'市场与开发',NULL,NULL,1,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (3033,'3032',NULL,'关键客户开发',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (3034,'3032',NULL,'关键渠道开发',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (3035,'3032',NULL,'获客效率优化',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (3036,'3032',NULL,'市场营销优化',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');

/*战略及策略*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1619,'1602',NULL,'公司的战略目标是否需要调整，如何调整',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1620,'1602',NULL,'具体的实现路径是否需要调整，如何调整',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1621,'1602',NULL,'切入点是否需要调整，如何调整',NULL,8,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'1','2000');

/*财务*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1714,'1702',NULL,'账面现金余额（元）',NULL,1,2,NULL,'o',0,'请填写金额',NULL,NULL,NULL,NULL,0,'2','10,2');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1715,'1702',NULL,'现金可以够公司存续几个月（月）',NULL,1,2,NULL,'o',0,'请填写',NULL,NULL,NULL,NULL,0,'2','3');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1716,'1702',NULL,'财务报表对运营数据的验证',NULL,2,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1717,'1702',NULL,'财务报表中的重大发现',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1718,'1702',NULL,'交割后事项落实',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1719,'1702',NULL,'遗留财务问题处理',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1720,'1702',NULL,'财务规范进度',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');

/*法务*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1817,'1812',NULL,'交割后事项落实',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1818,'1812',NULL,'遗留法务问题处理',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (1819,'1812',NULL,'法务规范进度',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');


/*融资及估值*/
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2067,'1902',NULL,'上一轮融资后关键运营指标的变化',NULL,10,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2068,'1902',NULL,'上一轮融资后技术、产品研发重大变化',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2069,'1902',NULL,'上一轮融资后公司资源等核心价值的变化',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2070,'1926',NULL,'下一轮融资的必要条件',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2071,'1926',NULL,'关键运营数据里程碑',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2072,'1926',NULL,'估值',NULL,20,2,'万元','o',0,NULL,NULL,NULL,NULL,NULL,0,'2','9,4');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2073,'1926',NULL,'下一轮的估值逻辑',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2074,'1926',NULL,'启动下一轮融资的时间点',NULL,1,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,'5',NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2075,'1926',NULL,'目标产业或战略投资人融资对象',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2076,'1926',NULL,'目标财务投资人融资对象',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2077,'1926',NULL,'隔一轮融资的关键运营数据及必要条件',NULL,8,2,NULL,'o',0,'请说明',NULL,NULL,NULL,NULL,0,'1','2000');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2078,'1926',NULL,'隔轮融资的估值及时间表',NULL,NULL,3,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL);
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2079,'2078',NULL,'隔轮融资估值',NULL,20,2,'万元','o',0,NULL,NULL,NULL,NULL,NULL,0,'2','9,4');
INSERT INTO `information_title` (`id`,`parent_id`,`code`,`name`,`index_no`,`type`,`sign`,`content`,`is_show`,`is_valid`,`placeholder`,`created_time`,`create_id`,`updated_time`,`update_id`,`is_must`,`val_rule`,`val_rule_mark`) VALUES (2080,'2078',NULL,'隔轮融资时间点',NULL,1,2,NULL,'o',0,NULL,NULL,NULL,NULL,NULL,0,'5',NULL);


INSERT INTO `information_listdata_remark` (`id`,`title_id`,`code`,`sub_code`,`name`,`field_1`,`sub_title_id1`,`field_2`,`sub_title_id2`,`field_3`,`sub_title_id3`,`field_4`,`sub_title_id4`,`field_5`,`sub_title_id5`,`field_6`,`sub_title_id6`,`field_7`,`sub_title_id7`,`field_8`,`sub_title_id8`,`field_9`,`sub_title_id9`,`field_10`,`sub_title_id10`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`,`fun_flag`) VALUES (20,3022,'grant-actual','grant-part','实际注资计划','实际注资名称',3037,'实际注资时间',3038,'实际注资金额',3039,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'0');



/*字典表增加字典项*/
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2205,NULL,NULL,'turnTo','是否经历了转向','D216',0,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2206,2205,1268,'turnTo1','已转向','D216_1',1,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2207,2205,1268,'turnTo2','正在转向','D216_2',2,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2208,2205,1268,'turnTo3','未转向','D216_3',3,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2209,NULL,NULL,'completeOnTime','达成该项目需要的核心能力不足部分的完善是否如期完成','D217',0,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2210,2209,1387,'completeOnTime1','超期完成','D217_1',1,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2211,2209,1387,'completeOnTime2','如期完成','D217_2',2,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2212,2209,1387,'completeOnTime3','延期完成','D217_3',3,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2213,2209,1387,'completeOnTime4','未完成','D217_4',4,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2214,NULL,NULL,'compareExecution','团队的执行力与创业当初比较是更优还是略逊','D218',0,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2215,2214,1388,'compareExecution1','更优','D218_1',1,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2216,2214,1388,'compareExecution2','持平','D218_2',2,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2217,2214,1388,'compareExecution3','略逊','D218_3',3,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2218,NULL,NULL,'entrepreneurialCulture','团队的创业文化是否形成','D219',0,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2219,2218,1390,'entrepreneurialCulture1','已形成','D219_1',1,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2220,2218,1390,'entrepreneurialCulture2','正在形成','D219_2',2,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2221,2218,1390,'entrepreneurialCulture3','未形成','D219_3',3,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2222,NULL,NULL,'dataRise','竞争是否导致运营数据增长趋缓或降低','D220',0,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2223,2222,1474,'dataRise1','竞争导致运营数据增长趋缓','D220_1',1,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2224,2222,1474,'dataRise2','竞争导致运营数据降低','D220_2',2,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2225,2222,1474,'dataRise3','无影响或影响很少','D220_3',3,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2226,NULL,NULL,'menaceVerify','对主要竞争威胁的对策是否验证','D221',0,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2227,2226,1576,'menaceVerify1','初步验证','D221_1',1,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2228,2226,1576,'menaceVerify2','验证','D221_2',2,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2229,2226,1576,'menaceVerify3','充分验证','D221_3',3,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2230,2226,1576,'menaceVerify4','尚未验证','D221_4',4,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2231,NULL,NULL,'financeVerify','财务报表对运营数据的验证','D222',0,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2232,2231,1716,'financeVerify1','初步验证','D222_1',1,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2233,2231,1716,'financeVerify2','验证','D222_2',2,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2234,2231,1716,'financeVerify3','充分验证','D222_3',3,0,NULL,NULL,NULL,NULL);
INSERT INTO `information_dictionary` (`id`,`parent_id`,`title_id`,`code`,`name`,`value`,`sort`,`is_valid`,`created_time`,`create_id`,`updated_time`,`update_id`) VALUES (2235,2231,1716,'financeVerify4','尚未验证','D222_4',4,0,NULL,NULL,NULL,NULL);

INSERT INTO `fx_db`.`information_dictionary` (`id`, `code`, `name`, `value`, `sort`, `is_valid`) VALUES ('2245', 'currency', '币种', 'D226', '0', '0');
INSERT INTO `fx_db`.`information_dictionary` (`id`, `parent_id`, `title_id`, `code`, `name`, `value`, `sort`, `is_valid`) VALUES ('2246', '2245', '2072', 'currency1', '人民币', 'D226_1', '1', '0');
INSERT INTO `fx_db`.`information_dictionary` (`id`, `parent_id`, `title_id`, `code`, `name`, `value`, `sort`, `is_valid`) VALUES ('2247', '2245', '2072', 'currency2', '美元', 'D226_2', '2', '0');
INSERT INTO `fx_db`.`information_dictionary` (`id`, `code`, `name`, `value`, `sort`, `is_valid`) VALUES ('2248', 'currency', '币种', 'D227', '0', '0');
INSERT INTO `fx_db`.`information_dictionary` (`id`, `parent_id`, `title_id`, `code`, `name`, `value`, `sort`, `is_valid`) VALUES ('2249', '2248', '2079', 'currency1', '人民币', 'D227_1', '1', '0');
INSERT INTO `fx_db`.`information_dictionary` (`id`, `parent_id`, `title_id`, `code`, `name`, `value`, `sort`, `is_valid`) VALUES ('2250', '2248', '2079', 'currency2', '美元', 'D227_2', '2', '0');


INSERT INTO `fx_db`.`information_title` (`id`, `parent_id`, `name`, `index_no`, `type`, `sign`, `is_show`, `is_valid`, `is_must`, `val_rule`, `val_rule_mark`) VALUES ('3037', '3022', '实际注资名称', '3062.7', '1', '2', 'f', '0', '0', '1', '20');
INSERT INTO `fx_db`.`information_title` (`id`, `parent_id`, `name`, `index_no`, `type`, `sign`, `is_show`, `is_valid`, `is_must`, `val_rule`) VALUES ('3038', '3022', '实际注资时间', '3062.8', '1', '2', 'f', '0', '0', '5');
INSERT INTO `fx_db`.`information_title` (`id`, `parent_id`, `name`, `index_no`, `type`, `sign`, `is_show`, `is_valid`, `is_must`, `val_rule`, `val_rule_mark`) VALUES ('3039', '3022', '实际注资金额', '3062.9', '1', '2', 'f', '0', '0', '2', '9,4');
